# Generated by Django 5.1.2 on 2024-10-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='weight_percentage',
        ),
    ]
