# Generated by Django 5.1.2 on 2024-10-27 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0002_remove_criterion_weight_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competition_app.competition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='competition_app.judge')),
                ('rounds', models.ManyToManyField(related_name='judge_assignments', to='competition_app.round')),
            ],
            options={
                'unique_together': {('judge', 'competition')},
            },
        ),
    ]
