# Generated by Django 5.1.2 on 2024-10-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0004_competition_show_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='expertise',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='judge',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/people.svg', null=True, upload_to='judge_profiles/'),
        ),
    ]
